### ISSUE TITLE
What are these flashcards man 😂😂😂

### ISSUE THREAD

**Issue by Lino091** [theshameer/GCSE-Resources#3]
What are these flashcards man 😂😂😂😂. I swear to god this is unedited and you can find this specific flashcard yourself if you look for it.

**Comment by Lino091** [comment]
@theshameer

**Comment by Kas330** [comment]
🤣🤣🤣🤣🤣🤣

**Comment by Lino091** [comment]
![image](https://github.com/user-attachments/assets/824b98e1-98d5-4f40-b40a-83e2d6d0ea5d)
